# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

project '/Users/mollypatterson/Documents/Calendar/ourCalendarApp/TestPOSIX/TestPOSIX.xcworkspace'

target 'TestPOSIX' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
use_frameworks!
  pod 'sqlite3'
  # Pods for TestPOSIX

    pod 'JTAppleCalendar', '~> 7.0'
      


end
